# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mod <- function(x, base) {
    .Call('_minVL_mod', PACKAGE = 'minVL', x, base)
}

get_vl_elt_distance <- function(e1, e2, elt_type) {
    .Call('_minVL_get_vl_elt_distance', PACKAGE = 'minVL', e1, e2, elt_type)
}

get_vl_ascending_distance <- function(e1, e2, elt_type) {
    .Call('_minVL_get_vl_ascending_distance', PACKAGE = 'minVL', e1, e2, elt_type)
}

#' Get voice-leading set distance
#'
#' Computes the voice-leading distance between two
#' ordered sets of the same length, after \insertRef{Tymoczko2006}{minVL}.
#' @param s1 First set (numeric vector)
#' @param s2 Second set (numeric vector)
#' @param elt_type Element type; can be "pitch" for MIDI pitches
#' or "pc" for pitch classes (character scalar)
#' @param norm Norm to use; can be "euclidean", "taxicab", or "infinity"
#' (character scalar)
#' @return Voice-leading distance between the two sets (numeric scalar)
#' @export
vl_dist <- function(s1, s2, elt_type = "pc", norm = "taxicab") {
    .Call('_minVL_vl_dist', PACKAGE = 'minVL', s1, s2, elt_type, norm)
}

order_by <- function(data, by) {
    .Call('_minVL_order_by', PACKAGE = 'minVL', data, by)
}

add_dist <- function(prev_dist, new_pair_dist, norm) {
    .Call('_minVL_add_dist', PACKAGE = 'minVL', prev_dist, new_pair_dist, norm)
}

#' Get minimal voice-leading
#'
#' Computes the minimal voice-leading between two sets of pitches or pitch classes, using the polynomial-time algorithm described in Tymoczko (2006).
#' @param s1 The first set to be compared; numeric vector, with each number corresponding to either a pitch or a pitch class. Duplicates are permitted, and they will be retained. Order does not matter.
#' @param s2 The second set to be compared; see \code{s1}.
#' @param elt_type Can be either \code{pitch} or \code{pc}; determines whether \code{s1} and \code{s2} are interpreted as pitches or pitch classes.
#' @param norm Can be either \code{euclidean}, \code{taxicab}, or \code{infinity}. Each of these identify different norms.
#' @return A list of three values: 1) the minimal voice-leading distance; 2) the corresponding start voicing; 3) the corresponding end voicing.
#' @references
#' \insertRef{Tymoczko2006}{minVL}
#' @export
min_vl <- function(s1, s2, elt_type = "pc", norm = "taxicab") {
    .Call('_minVL_min_vl', PACKAGE = 'minVL', s1, s2, elt_type, norm)
}

