# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mod <- function(x, base) {
    .Call('_vldist_mod', PACKAGE = 'vldist', x, base)
}

#' Get voice-leading element distance
#'
#' Computes the voice-leading distance between two
#' elements <e1> and <e2> given <elt_type>. <elt_type>
#' can be "pc", in which case the distance
#' is computed between two pitch classes, or
#' "pitch", in which cases distance is computed
#' between two pitches.
get_vl_elt_distance <- function(e1, e2, elt_type) {
    .Call('_vldist_get_vl_elt_distance', PACKAGE = 'vldist', e1, e2, elt_type)
}

#' Get voice-leading ascending distance
#'
#' Returns the ascending distance from <e1> to <e2>,
#' after Tymoczko (2006): the smallest nonnegative real
#' number x such that, if p is a pitch with label e1,
#' then p + x has label e2. <elt-type> may be either
#' "pitch" or "pc; it denotes whether <e1>
#' and <e2> are pitches or pitch classes.
#' Vectorised over <e2>.
get_vl_ascending_distance <- function(e1, e2, elt_type) {
    .Call('_vldist_get_vl_ascending_distance', PACKAGE = 'vldist', e1, e2, elt_type)
}

#' Get voice-leading set distance
#'
#' Computes the voice-leading distance between two
#' ordered sets of the same length, <s1> and <s2>,
#' given <elt-type> (which can either be
#' :pitch or :pitch-class; see vl-elt-distance for
#' definition) and <norm>, which determines the
#' norm used: currently <norm> can take values
#' of :euclidean, :taxicab, and :infinity.
#' @export
get_vl_set_distance <- function(s1, s2, elt_type, norm) {
    .Call('_vldist_get_vl_set_distance', PACKAGE = 'vldist', s1, s2, elt_type, norm)
}

order_by <- function(data, by) {
    .Call('_vldist_order_by', PACKAGE = 'vldist', data, by)
}

add_dist <- function(prev_dist, new_pair_dist, norm) {
    .Call('_vldist_add_dist', PACKAGE = 'vldist', prev_dist, new_pair_dist, norm)
}

#' Get minimal voice-leading
#'
#' Computes the minimal voice-leading between two sets of pitches or pitch classes, using the polynomial-time algorithm described in Tymoczko (2006).
#' @param s1 The first set to be compared; numeric vector, with each number corresponding to either a pitch or a pitch class. Duplicates are permitted, and they will be retained. Order does not matter.
#' @param s2 The second set to be compared; see \code{s1}.
#' @param elt_type Can be either \code{pitch} or \code{pc}; determines whether \code{s1} and \code{s2} are interpreted as pitches or pitch classes.
#' @param norm Can be either \code{euclidean}, \code{taxicab}, or \code{infinity}. Each of these identify different norms.
#' @return A list of three values: 1) the size of the minimal voice-leading; 2) the start voicing; 3) the end voicing.
#' @references
#' \insertRef{Tymoczko2006}{vldist}
#' @export
get_minimal_voice_leading <- function(s1, s2, elt_type = "pc", norm = "taxicab") {
    .Call('_vldist_get_minimal_voice_leading', PACKAGE = 'vldist', s1, s2, elt_type, norm)
}

